export type Category = "Feminino" | "Masculino" | "Unissex" | "Presentes";

export const categories: Category[] = [
  "Feminino",
  "Masculino",
  "Unissex",
  "Presentes",
];

export type Note = {
  top: string[];
  heart: string[];
  base: string[];
};

export type Product = {
  slug: string;
  name: string;
  brand: string;
  category: Category;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  size: string;
  image: string;
  badge?: string;
  featured?: boolean;
  inStock: boolean;
  description: string;
  notes: Note;
};

export const products: Product[] = [
  {
    slug: "amber-rouge",
    name: "Amber Rouge",
    brand: "Orientica",
    category: "Unissex",
    price: 519.9,
    originalPrice: 579.9,
    rating: 4.9,
    reviews: 326,
    size: "80ml",
    image: "/perfumes/amber-rouge.png",
    badge: "Best Seller",
    featured: true,
    inStock: true,
    description:
      "Um âmbar doce e hipnótico que se tornou um clássico viral. Açafrão e jasmim sobre uma base amadeirada dourada, com rastro intenso e duradouro.",
    notes: {
      top: ["Açafrão"],
      heart: ["Jasmim"],
      base: ["Âmbar-Forte", "Cedro", "Resina"],
    },
  },
  {
    slug: "khamrah-waha",
    name: "Khamrah Waha",
    brand: "Lattafa",
    category: "Unissex",
    price: 469.9,
    rating: 4.8,
    reviews: 187,
    size: "100ml",
    image: "/perfumes/khamrah-waha.jpg",
    badge: "Novo",
    featured: false,
    inStock: true,
    description:
      "Uma edição mais quente do icônico Khamrah: tâmaras, coco e pralinê envolvidos em baunilha e âmbar. Acolhedor e inesquecível.",
    notes: {
      top: ["Tâmara", "Canela"],
      heart: ["Pralinê", "Coco"],
      base: ["Baunilha", "Âmbar", "Fava Tonka"],
    },
  },
  {
    slug: "atheeri",
    name: "Atheeri",
    brand: "Lattafa",
    category: "Feminino",
    price: 469.9,
    rating: 4.7,
    reviews: 96,
    size: "100ml",
    image: "/perfumes/atheeri.jpg",
    featured: false,
    inStock: true,
    description:
      "Um floral frutado luminoso para o dia a dia. Pêra e jasmim sobre uma base almiscarada, leve e elegante.",
    notes: {
      top: ["Pêra"],
      heart: ["Jasmim", "Flor de Laranjeira"],
      base: ["Almíscar", "Âmbar"],
    },
  },
  {
    slug: "supremacy-silver",
    name: "Supremacy Silver",
    brand: "Afnan",
    category: "Masculino",
    price: 299.9,
    rating: 4.7,
    reviews: 134,
    size: "100ml",
    image: "/perfumes/supremacy-silver.png",
    featured: false,
    inStock: true,
    description:
      "Frescor cítrico com alma aquática. Bergamota, abacaxi e groselha negra em uma composição vibrante e versátil.",
    notes: {
      top: ["Bergamota", "Abacaxi"],
      heart: ["Groselha Negra"],
      base: ["Almíscar", "Âmbar Cinzento"],
    },
  },
  {
    slug: "club-de-nuit-bling",
    name: "Club de Nuit Bling",
    brand: "Armaf",
    category: "Feminino",
    price: 379.9,
    rating: 4.6,
    reviews: 88,
    size: "75ml",
    image: "/perfumes/club-de-nuit-bling.jpg",
    featured: false,
    inStock: true,
    description:
      "Um buquê delicado de flores brancas com frutas frescas. Suave, feminino e cheio de presença.",
    notes: {
      top: ["Pêra", "Groselha"],
      heart: ["Jasmim", "Peônia"],
      base: ["Almíscar Branco"],
    },
  },
  {
    slug: "jouri",
    name: "Jouri",
    brand: "Lattafa",
    category: "Feminino",
    price: 409.9,
    rating: 4.8,
    reviews: 112,
    size: "100ml",
    image: "/perfumes/jouri.jpg",
    featured: false,
    inStock: true,
    description:
      "Rosas aveludadas com açafrão e um toque de oud. Sofisticada, intensa e marcante.",
    notes: {
      top: ["Açafrão"],
      heart: ["Rosa Damascena"],
      base: ["Oud", "Âmbar", "Almíscar"],
    },
  },
  {
    slug: "club-de-nuit-intense-man",
    name: "Club de Nuit Intense Man 105ml",
    brand: "Armaf",
    category: "Masculino",
    price: 299.9,
    originalPrice: 339.9,
    rating: 4.9,
    reviews: 512,
    size: "105ml",
    image: "/perfumes/club-de-nuit-intense-man.jpg",
    badge: "Best Seller",
    featured: true,
    inStock: true,
    description:
      "O lendário \"intense\" que conquistou o mundo. Abacaxi defumado, musgo e âmbar em um rastro de respeito e presença. Versão francesa.",
    notes: {
      top: ["Abacaxi", "Bergamota"],
      heart: ["Bétula", "Groselha Negra"],
      base: ["Almíscar", "Âmbar", "Musgo de Carvalho"],
    },
  },
  {
    slug: "delilah-blanc",
    name: "Delilah Blanc",
    brand: "Alhambra",
    category: "Feminino",
    price: 279.9,
    rating: 4.8,
    reviews: 143,
    size: "100ml",
    image: "/perfumes/delilah-blanc.jpg",
    featured: false,
    inStock: true,
    description:
      "Uma versão mais etérea e fresca do icônico Delilah. Lichia e ruibarbo com um coração de rosas delicado.",
    notes: {
      top: ["Lichia", "Ruibarbo"],
      heart: ["Rosa", "Peônia"],
      base: ["Almíscar", "Madeiras Claras"],
    },
  },
  {
    slug: "angham",
    name: "Angham",
    brand: "Lattafa",
    category: "Feminino",
    price: 239.9,
    rating: 4.8,
    reviews: 167,
    size: "100ml",
    image: "/perfumes/angham.png",
    badge: "Novo",
    featured: false,
    inStock: true,
    description:
      "Baunilha cremosa com lavanda e gengibre. Confortável, elegante e impossível de ignorar.",
    notes: {
      top: ["Gengibre", "Bergamota"],
      heart: ["Lavanda"],
      base: ["Baunilha", "Âmbar"],
    },
  },
  {
    slug: "asad",
    name: "Asad",
    brand: "Lattafa",
    category: "Masculino",
    price: 269.9,
    originalPrice: 299.9,
    rating: 4.8,
    reviews: 231,
    size: "100ml",
    image: "/perfumes/asad.jpg",
    badge: "Favorito",
    featured: true,
    inStock: true,
    description:
      "O elixir marcante inspirado nas notas mais desejadas do momento. Lavanda, pimenta e baunilha em um abraço esfumaçado.",
    notes: {
      top: ["Bergamota", "Pimenta"],
      heart: ["Lavanda", "Canela"],
      base: ["Baunilha", "Âmbar", "Pralinê"],
    },
  },
  {
    slug: "asad-bourbon",
    name: "Asad Bourbon",
    brand: "Lattafa",
    category: "Masculino",
    price: 319.9,
    rating: 4.7,
    reviews: 129,
    size: "100ml",
    image: "/perfumes/asad-bourbon.jpg",
    featured: false,
    inStock: true,
    description:
      "O clássico Asad com um twist amadeirado e licoroso. Âmbar, baunilha e fava tonka para as noites especiais.",
    notes: {
      top: ["Pimenta Rosa"],
      heart: ["Bourbon", "Baunilha"],
      base: ["Âmbar", "Fava Tonka", "Madeiras"],
    },
  },
  {
    slug: "fakhar-black",
    name: "Fakhar Black",
    brand: "Lattafa",
    category: "Masculino",
    price: 289.9,
    rating: 4.7,
    reviews: 156,
    size: "100ml",
    image: "/perfumes/fakhar-black.png",
    featured: false,
    inStock: true,
    description:
      "Um fougère moderno e versátil: maçã, lavanda e gengibre com fundo amadeirado fresco. O equilíbrio perfeito entre casual e elegante.",
    notes: {
      top: ["Maçã", "Bergamota"],
      heart: ["Lavanda", "Gengibre"],
      base: ["Cedro", "Âmbar", "Madeiras"],
    },
  },
  {
    slug: "fakhar-gold",
    name: "Fakhar Gold",
    brand: "Lattafa",
    category: "Feminino",
    price: 229.9,
    rating: 4.8,
    reviews: 0,
    size: "100ml",
    image: "/perfumes/fakhar-gold.png",
    badge: "Novo",
    featured: false,
    inStock: true,
    description:
      "A edição extrait do icônico Fakhar: acordes orientais ricos e envolventes. Toranja e cardamomo sobre coração floral de tuberosa, com base ambarada e couro.",
    notes: {
      top: ["Toranja", "Pimenta Rosa", "Cardamomo"],
      heart: ["Artemísia", "Notas Solares", "Tuberosa"],
      base: ["Cashmeran", "Âmbar", "Ládano", "Couro"],
    },
  },
  {
    slug: "fakhar-rose",
    name: "Fakhar Rose",
    brand: "Lattafa",
    category: "Feminino",
    price: 299.9,
    rating: 4.6,
    reviews: 94,
    size: "100ml",
    image: "/perfumes/fakhar-rose.jpg",
    featured: false,
    inStock: true,
    description:
      "Rosas suculentas com frutas vermelhas e almíscar. Romântica, moderna e cheia de charme.",
    notes: {
      top: ["Frutas Vermelhas"],
      heart: ["Rosa"],
      base: ["Almíscar Branco"],
    },
  },
  {
    slug: "khamrah",
    name: "Khamrah",
    brand: "Lattafa",
    category: "Unissex",
    price: 229.9,
    originalPrice: 259.9,
    rating: 4.9,
    reviews: 486,
    size: "100ml",
    image: "/perfumes/khamrah.jpg",
    badge: "Best Seller",
    featured: true,
    inStock: true,
    description:
      "O gourmand dourado que virou febre: tâmaras, canela e pralinê sobre baunilha e âmbar. Quente, doce e inesquecível.",
    notes: {
      top: ["Canela", "Noz-Moscada"],
      heart: ["Tâmara", "Pralinê"],
      base: ["Baunilha", "Âmbar", "Fava Tonka"],
    },
  },
  {
    slug: "khamrah-qahwa",
    name: "Khamrah Qahwa",
    brand: "Lattafa",
    category: "Unissex",
    price: 229.9,
    rating: 4.9,
    reviews: 342,
    size: "100ml",
    image: "/perfumes/khamrah-qahwa.png",
    badge: "Novo",
    featured: true,
    inStock: true,
    description:
      "Khamrah com um coração de café: caramelizado, cremoso e ainda mais viciante. Doce na medida certa.",
    notes: {
      top: ["Canela", "Cardamomo"],
      heart: ["Café", "Caramelo"],
      base: ["Baunilha", "Âmbar", "Tonka"],
    },
  },
  {
    slug: "yara-candy",
    name: "Yara Candy",
    brand: "Lattafa",
    category: "Feminino",
    price: 229.9,
    rating: 4.7,
    reviews: 201,
    size: "100ml",
    image: "/perfumes/yara-candy.jpg",
    featured: false,
    inStock: true,
    description:
      "Delícia açucarada de frutas vermelhas com jasmim e baunilha. Doce, jovem e contagiante.",
    notes: {
      top: ["Frutas Vermelhas"],
      heart: ["Jasmim"],
      base: ["Baunilha", "Almíscar"],
    },
  },
  {
    slug: "yara-elixir",
    name: "Yara Elixir",
    brand: "Lattafa",
    category: "Feminino",
    price: 289.9,
    originalPrice: 319.9,
    rating: 4.8,
    reviews: 189,
    size: "100ml",
    image: "/perfumes/yara-elixir.jpg",
    badge: "Novo",
    featured: true,
    inStock: true,
    description:
      "Uma versão intensa da queridinha Yara: cremosa, frutada e com presença maior. Para quem ama marcantes.",
    notes: {
      top: ["Frutas Vermelhas"],
      heart: ["Jasmim", "Flor de Laranjeira"],
      base: ["Baunilha", "Âmbar"],
    },
  },
  {
    slug: "yara-moi",
    name: "Yara Moi",
    brand: "Lattafa",
    category: "Feminino",
    price: 229.9,
    rating: 4.7,
    reviews: 133,
    size: "100ml",
    image: "/perfumes/yara-moi.jpg",
    featured: false,
    inStock: true,
    description:
      "Uma interpretação mais fresca da Yara: peras suculentas, rosas e almíscar limpo.",
    notes: {
      top: ["Pêra"],
      heart: ["Rosa"],
      base: ["Almíscar Branco"],
    },
  },
  {
    slug: "yara-rosa",
    name: "Yara Rose",
    brand: "Lattafa",
    category: "Feminino",
    price: 249.9,
    rating: 4.6,
    reviews: 118,
    size: "100ml",
    image: "/perfumes/yara-rosa.jpg",
    featured: false,
    inStock: true,
    description:
      "O clássico Yara em toda a sua doçura: tangerina e orquídea com coração tropical gourmand, sobre baunilha, sândalo e almíscar.",
    notes: {
      top: ["Tangerina", "Heliotrópio", "Orquídea"],
      heart: ["Notas Tropicais", "Gourmand"],
      base: ["Baunilha", "Sândalo", "Almíscar"],
    },
  },
  {
    slug: "yara-tous",
    name: "Yara Tous",
    brand: "Lattafa",
    category: "Feminino",
    price: 229.9,
    rating: 4.6,
    reviews: 102,
    size: "100ml",
    image: "/perfumes/yara-tous.jpg",
    featured: false,
    inStock: true,
    description:
      "Uma Yara clara e luminosa, com notas doces suaves e fundo ambarado. Versátil para qualquer ocasião.",
    notes: {
      top: ["Frutas Doces"],
      heart: ["Flor de Laranjeira"],
      base: ["Âmbar", "Almíscar"],
    },
  },
  {
    slug: "baroque-rouge-540-branco",
    name: "Baroque Rouge 540 Branco",
    brand: "Alhambra",
    category: "Feminino",
    price: 269.9,
    originalPrice: 299.9,
    rating: 4.9,
    reviews: 287,
    size: "100ml",
    image: "/perfumes/baroque-rouge-540-branco.jpg",
    badge: "Edição Limitada",
    featured: true,
    inStock: true,
    description:
      "O açafrão dourado e o jasmim sobre âmbar-forte: a assinatura doce e amadeirada que deixa rastro por onde passa.",
    notes: {
      top: ["Açafrão"],
      heart: ["Jasmim"],
      base: ["Âmbar-Forte", "Cedro"],
    },
  },
  {
    slug: "baroque-rouge-extrait-vermelho",
    name: "Baroque Rouge Extrait Vermelho",
    brand: "Alhambra",
    category: "Feminino",
    price: 279.9,
    rating: 4.9,
    reviews: 254,
    size: "100ml",
    image: "/perfumes/baroque-rouge-extrait-vermelho.png",
    featured: false,
    inStock: true,
    description:
      "A versão extrait, mais intensa e mais doce, com resinas escuras e um toque floral envolvente.",
    notes: {
      top: ["Açafrão", "Amêndoa"],
      heart: ["Jasmim", "Flor de Laranjeira"],
      base: ["Âmbar-Forte", "Resinas"],
    },
  },
  {
    slug: "candid-scandal",
    name: "Candid Scandal",
    brand: "Alhambra",
    category: "Feminino",
    price: 299.9,
    rating: 4.7,
    reviews: 121,
    size: "100ml",
    image: "/perfumes/candid-scandal.png",
    featured: false,
    inStock: true,
    description:
      "Gardênia e mel sobre um coração cremoso de caramelo. Escandalosamente feminina.",
    notes: {
      top: ["Mandarina"],
      heart: ["Gardênia", "Mel"],
      base: ["Caramelo", "Baunilha"],
    },
  },
  {
    slug: "candid-tonight-scandal-night",
    name: "Candid Tonight Scandal Night",
    brand: "Alhambra",
    category: "Feminino",
    price: 299.9,
    rating: 4.6,
    reviews: 87,
    size: "100ml",
    image: "/perfumes/candid-tonight-scandal-night.png",
    featured: false,
    inStock: true,
    description:
      "A versão noturna: mel escuro, jasmim e fava tonka em uma composição mais ousada e envolvente.",
    notes: {
      top: ["Flor de Laranjeira"],
      heart: ["Mel", "Jasmim"],
      base: ["Fava Tonka", "Patchouli"],
    },
  },
  {
    slug: "como-coco-mademoiselle",
    name: "Como Coco Mademoiselle",
    brand: "Alhambra",
    category: "Feminino",
    price: 299.9,
    rating: 4.8,
    reviews: 176,
    size: "100ml",
    image: "/perfumes/como-coco-mademoiselle.jpg",
    featured: false,
    inStock: true,
    description:
      "A elegância de um floral chipre: laranja, rosas e jasmim sobre patchouli e baunilha.",
    notes: {
      top: ["Laranja"],
      heart: ["Rosa", "Jasmim"],
      base: ["Patchouli", "Baunilha"],
    },
  },
  {
    slug: "delilah",
    name: "Delilah",
    brand: "Alhambra",
    category: "Feminino",
    price: 249.9,
    originalPrice: 279.9,
    rating: 4.8,
    reviews: 198,
    size: "100ml",
    image: "/perfumes/delilah.jpg",
    badge: "Favorito",
    featured: false,
    inStock: true,
    description:
      "O floral de rosas mais desejado: lichia, ruibarbo e peônia sobre almíscar. Sofisticado e feminino.",
    notes: {
      top: ["Lichia", "Ruibarbo"],
      heart: ["Rosa", "Peônia"],
      base: ["Almíscar", "Âmbar"],
    },
  },
  {
    slug: "club-de-nuit-overdose",
    name: "Club de Nuit Overdose",
    brand: "Armaf",
    category: "Unissex",
    price: 449.9,
    rating: 4.7,
    reviews: 145,
    size: "105ml",
    image: "/perfumes/club-de-nuit-overdose.jpg",
    featured: false,
    inStock: true,
    description:
      "Uma edição intensa com tabaco e couro sobre o frescor cítrico característico da linha. Marcante à noite.",
    notes: {
      top: ["Limão", "Abacaxi"],
      heart: ["Tabaco", "Couro"],
      base: ["Âmbar", "Musgo"],
    },
  },
  {
    slug: "club-de-nuit-milestone",
    name: "Club de Nuit Milestone",
    brand: "Armaf",
    category: "Unissex",
    price: 299.9,
    rating: 4.6,
    reviews: 119,
    size: "105ml",
    image: "/perfumes/club-de-nuit-milestone.jpg",
    featured: false,
    inStock: true,
    description:
      "Melancia fresca e âmbar cinzento marinho: uma fragrância aquática elegante, perfeita para o verão.",
    notes: {
      top: ["Melancia", "Sal Marinho"],
      heart: ["Íris", "Almíscar"],
      base: ["Âmbar Cinzento"],
    },
  },
  {
    slug: "club-de-nuit-iconic",
    name: "Club de Nuit Iconic",
    brand: "Armaf",
    category: "Unissex",
    price: 339.9,
    rating: 4.8,
    reviews: 232,
    size: "105ml",
    image: "/perfumes/club-de-nuit-iconic.jpg",
    badge: "Novo",
    featured: false,
    inStock: true,
    description:
      "Amadeirado sofisticado com um toque cítrico: cedro, sândalo e âmbar em equilíbrio perfeito.",
    notes: {
      top: ["Bergamota"],
      heart: ["Cedro"],
      base: ["Sândalo", "Âmbar"],
    },
  },
  {
    slug: "royal-amber",
    name: "Royal Amber",
    brand: "Orientica",
    category: "Unissex",
    price: 529.9,
    rating: 4.8,
    reviews: 164,
    size: "80ml",
    image: "/perfumes/royal-amber.jpg",
    featured: false,
    inStock: true,
    description:
      "Âmbar real, resinoso e envolvente, com um toque de baunilha. Presença marcante para quem quer ser lembrado.",
    notes: {
      top: ["Bergamota", "Açafrão"],
      heart: ["Âmbar"],
      base: ["Baunilha", "Oud"],
    },
  },
  {
    slug: "hawas-for-him",
    name: "Hawas For Him",
    brand: "Rasasi",
    category: "Masculino",
    price: 249.9,
    originalPrice: 279.9,
    rating: 4.8,
    reviews: 298,
    size: "100ml",
    image: "/perfumes/hawas-for-him.jpg",
    badge: "Favorito",
    featured: true,
    inStock: true,
    description:
      "O aquático mais cobiçado: toranja, canela e notas marinhas sobre âmbar. Fresco, doce e elogiado por todos.",
    notes: {
      top: ["Toranja", "Maçã"],
      heart: ["Canela", "Notas Marinhas"],
      base: ["Âmbar", "Almíscar"],
    },
  },
  {
    slug: "hawas-black",
    name: "Hawas Black",
    brand: "Rasasi",
    category: "Masculino",
    price: 309.9,
    rating: 4.7,
    reviews: 173,
    size: "100ml",
    image: "/perfumes/hawas-black.jpg",
    featured: false,
    inStock: true,
    description:
      "A versão escura e intensa do Hawas: ameixa defumada, tabaco e âmbar profundo.",
    notes: {
      top: ["Ameixa"],
      heart: ["Tabaco"],
      base: ["Âmbar", "Madeiras Escuras"],
    },
  },
  {
    slug: "sabah-al-ward",
    name: "Sabah Al Ward",
    brand: "Al Wataniah",
    category: "Feminino",
    price: 229.9,
    rating: 4.8,
    reviews: 76,
    size: "100ml",
    image: "/perfumes/sabah-al-ward.png",
    badge: "Novo",
    featured: false,
    inStock: true,
    description:
      "O \"amanhecer das rosas\": floral oriental que une cacau, flor de laranjeira e jasmim sambac sobre baunilha e patchouli. Doce, elegante e com presença marcante.",
    notes: {
      top: ["Pimenta Rosa", "Tangerina"],
      heart: ["Cacau", "Flor de Laranjeira", "Jasmim Sambac"],
      base: ["Baunilha", "Fava Tonka", "Patchouli"],
    },
  },
  {
    slug: "durrat-al-aroos",
    name: "Durrat Al Aroos",
    brand: "Al Wataniah",
    category: "Feminino",
    price: 219.9,
    rating: 4.7,
    reviews: 64,
    size: "100ml",
    image: "/perfumes/durrat-al-aroos.jpg",
    featured: false,
    inStock: true,
    description:
      "A \"pérola da noiva\": oriental sofisticado com almíscar branco, baunilha e açafrão sobre madeiras quentes. A elegância da perfumaria árabe.",
    notes: {
      top: ["Almíscar Branco", "Cipriol"],
      heart: ["Baunilha", "Cardamomo", "Açafrão"],
      base: ["Fava Tonka", "Madeira Guaiac"],
    },
  },
  {
    slug: "attar-al-wesal",
    name: "Attar Al Wesal",
    brand: "Al Wataniah",
    category: "Unissex",
    price: 209.9,
    rating: 4.7,
    reviews: 89,
    size: "100ml",
    image: "/perfumes/attar-al-wesal.jpg",
    featured: false,
    inStock: true,
    description:
      "Um contraste sedutor entre frescor e calor: pêra e hortelã abrem para canela e sálvia, com fundo cremoso de baunilha preta e âmbar.",
    notes: {
      top: ["Pêra", "Lavanda", "Hortelã", "Bergamota"],
      heart: ["Canela", "Sálvia", "Cominho"],
      base: ["Baunilha Preta", "Âmbar", "Patchouli", "Cedro"],
    },
  },
  {
    slug: "ana-abiyedh-rouge",
    name: "Ana Abiyedh Rouge",
    brand: "Lattafa",
    category: "Unissex",
    price: 189.9,
    rating: 4.7,
    reviews: 158,
    size: "60ml",
    image: "/perfumes/ana-abiyedh-rouge.png",
    badge: "Novo",
    featured: false,
    inStock: true,
    description:
      "A interpretação mais acessível do DNA âmbar-forte: frutado, doce e almiscarado, com caramelo e âmbar cinzento. Um segredo entre os perfumistas.",
    notes: {
      top: ["Pêra Nashi", "Kumquat", "Bergamota"],
      heart: ["Caramelo", "Gerânio"],
      base: ["Âmbar Cinzento", "Almíscar", "Musgo de Carvalho"],
    },
  },
  {
    slug: "afeef",
    name: "Afeef EDP",
    brand: "Lattafa",
    category: "Unissex",
    price: 579.9,
    rating: 4.8,
    reviews: 52,
    size: "100ml",
    image: "/perfumes/afeef.png",
    badge: "Novo",
    featured: false,
    inStock: true,
    description:
      "O lançamento mais desejado da Lattafa: pêssego e tuberosa sobre pralinê e sândalo. Um floral frutado cremoso, sofisticado e viciante.",
    notes: {
      top: ["Pêssego", "Pimenta Rosa", "Bergamota"],
      heart: ["Tuberosa", "Jasmim", "Flor de Laranjeira"],
      base: ["Pralinê", "Sândalo", "Âmbar", "Patchouli"],
    },
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured).slice(0, 8);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  const sameCategory = products.filter(
    (p) => p.slug !== product.slug && p.category === product.category
  );
  const others = products.filter(
    (p) => p.slug !== product.slug && p.category !== product.category
  );
  return [...sameCategory, ...others].slice(0, limit);
}
